create table accounts (
  id bigint generated by default as identity,
  username varchar(100) not null unique,
  password_hash varchar(255) not null,
  primary key (id)
);

create table addresses (
  id bigint generated by default as identity,
  street varchar(255) not null,
  city varchar(100) not null,
  state varchar(100) not null,
  zip_code varchar(20) not null,
  primary key (id)
);

create table customers (
  id varchar(36) not null,
  name varchar(200) not null,
  email varchar(255) not null unique,
  account_id bigint,
  shipping_address_id bigint,
  primary key (id)
);

create table carts (
  id bigint generated by default as identity,
  customer_id varchar(36) not null unique,
  primary key (id)
);

create table cart_items (
  id bigint generated by default as identity,
  cart_id bigint not null,
  product_id varchar(36) not null,
  quantity integer not null,
  primary key (id)
);

create table products (
  id varchar(36) not null,
  name varchar(200) not null,
  description varchar(1000),
  price numeric(38,2) not null,
  stock_quantity integer not null,
  category enum ('BOOKS','CLOTHING','ELECTRONICS','GROCERY','HOME_GOODS') not null,
  primary key (id)
);

create table orders (
  id varchar(36) not null,
  customer_id varchar(36) not null,
  order_date timestamp(6) not null,
  total_amount numeric(38,2) not null,
  shipping_street varchar(255),
  shipping_city varchar(100),
  shipping_state varchar(100),
  shipping_zip_code varchar(20),
  status enum ('CANCELLED','DELIVERED','PENDING_PAYMENT','PLACED','RETURNED','SHIPPED') not null,
  primary key (id)
);

create table order_line_items (
  id bigint generated by default as identity,
  order_id varchar(36) not null,
  product_id varchar(36) not null,
  product_name varchar(200),
  quantity integer not null,
  price_at_purchase numeric(38,2) not null,
  primary key (id)
);

create table payments (
  id varchar(36) not null,
  customer_id varchar(36) not null,
  order_id varchar(36),
  amount numeric(38,2) not null,
  currency varchar(10) not null,
  method varchar(30) not null,
  idempotency_key varchar(100) not null unique,
  transaction_id varchar(200),
  gateway_response TEXT,
  status enum ('COMPLETED','FAILED','PENDING','REFUNDED') not null,
  created_at timestamp(6) not null,
  updated_at timestamp(6) not null,
  primary key (id)
);

create index idx_order_customer on orders (customer_id);
create index idx_order_status on orders (status);
create index idx_payment_customer on payments (customer_id);
create index idx_payment_order on payments (order_id);
create index idx_payment_status on payments (status);
create index idx_product_name on products (name);
create index idx_product_category on products (category);

alter table cart_items add constraint fk_cart_items_cart foreign key (cart_id) references carts (id);
alter table customers add constraint fk_customers_account foreign key (account_id) references accounts (id);
alter table customers add constraint fk_customers_shipping_address foreign key (shipping_address_id) references addresses (id);
alter table order_line_items add constraint fk_order_line_items_order foreign key (order_id) references orders (id);
